FROM __HPN_IMAGE_NAME__
LABEL maintainer="François Lamboley <francois.lamboley@happn.com>"
LABEL description="A docker image that contains the Swift compiler"

RUN rm "/usr/local/bin/build_swift_package.sh"
CMD "/bin/bash"
